### ISSUE TITLE
Fab Rev A

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen121nissan-issues#1]
![image](https://user-images.githubusercontent.com/48498823/122318925-de796200-ceed-11eb-99bf-ab29318610b3.png)

Hold on, that's not the jack and USB placement I was shown. Are those latest gerbers or not?

![image](https://user-images.githubusercontent.com/48498823/122319165-3e700880-ceee-11eb-9390-94ea5cdcb190.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/122408078-187b5000-cf50-11eb-91a9-38ad1c90d081.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/122410775-377ae180-cf52-11eb-9c15-aa8fd88a2c61.png)

**Comment by rusefillc** [comment]
D420 fixed

just ordered:

![image](https://user-images.githubusercontent.com/48498823/122412560-ac025000-cf53-11eb-966b-ef060216363c.png)

and

![image](https://user-images.githubusercontent.com/48498823/122412598-b45a8b00-cf53-11eb-94a5-8349e7f9980e.png)

**Comment by rusefillc** [comment]
@Qwerty-OFF can you please help with mouser part numbers for the two missing parts? since boards were ordered without output drivers we can choose whatever better parts.

another thing maybe it's possible to alter the order BOM if we find an available part. Do we see any JLC options?

**Comment by rusefillc** [comment]
Let me try adjusting BOM in the "in production" order

Q305, Q306, Q307, Q308, Q309, Q310
ZXMS6005SGTA is C174042

**Comment by Qwerty-OFF** [comment]
AP2331W-7
https://eu.mouser.com/ProductDetail/Diodes-Incorporated/AP2331W-7?qs=L1DZKBg7t5HrPbB%252BSrOPSA%3D%3D

ZXMS6005SGTA
https://eu.mouser.com/ProductDetail/Diodes-Incorporated/ZXMS6005SGTA?qs=%2Fha2pyFaduha5y2MtIIYgNoENYyVSO9vpB04KyNN0BUrsklJ0Gdhaw%3D%3D

**Comment by rusefillc** [comment]
See also https://github.com/andreika-git/hellen-one/issues/71

**Comment by rusefillc** [comment]
Drama - without 176 MCU what was actually fabricated is rev B with 144 MCU
