### ISSUE TITLE
No need to have custom of duplicated connector footprints

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen121nissan-issues#11]
https://github.com/rusefi/hellen121nissan references https://github.com/rusefi/kicad-libraries

https://github.com/rusefi/kicad-libraries has https://github.com/rusefi/kicad-libraries/blob/master/368255-2.lib https://github.com/rusefi/kicad-libraries/blob/master/rusefi_lib.pretty/368255-2.kicad_mod

whatever fixes/changed should be done in https://github.com/rusefi/kicad-libraries/ not a custom copy of the footprint unless there are reasons.

**Comment by Qwerty-OFF** [comment]
https://github.com/rusefi/kicad-libraries contains symbols in the old *.lib format. Kicad 5.99 can use these symbols, but cannot edit them. We will have to use old versions of kicad for editing, or convert symbols to the new * .kicad_sym format, which is not compatible with old versions of Kicad

**Comment by rusefillc** [comment]
we need new stuff in the shared lib since that's the future

files which have to have two separate version - 5 and 6 - maybe we would have to use different file names temporary "_version_6.bla bla" but we definitely need files in share libs :)

For right now while we are actively changing stuff let's at least make file names unique, we can clean up the mess once the dust settles

**Comment by Qwerty-OFF** [comment]
There will be a synchronization problem between the old and new version of the components. For example, if I change the footprint of a connector in the *.kicad_sym file, the changes will not appear automatically in the old *.lib. Will we do these changes manually in the old version of Kicad?

**Comment by Qwerty-OFF** [comment]
Using kicad6-libraries in new projects
