### ISSUE TITLE
schematic not readable 

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen121nissan-issues#12]
R19 R25 see how these labels are under the resistors
![image](https://user-images.githubusercontent.com/48498823/129086647-853ea9a3-44cf-4507-935d-314e352e90b6.png)

**Comment by Qwerty-OFF** [comment]
Fixed
![image](https://user-images.githubusercontent.com/4116383/160005888-524948ed-e21d-4123-90d9-ab1051d52b24.png)
