### ISSUE TITLE
fab same gerbers with corrected BOM

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen121nissan-issues#16]
op-amp
R8
shortage https://github.com/rusefi/hellen-NA8-96-issues/issues/6

**Comment by Qwerty-OFF** [comment]
Done https://github.com/rusefi/hellen121nissan/blob/main/boards/hellen121nissan-b/board/hellen121nissan-b-BOM-fix.csv
INJ low side, ETB drver and MCU out of stock

We must not forget to make changes in next-rev project.

**Comment by rusefillc** [comment]
Waiting to see if they would restock INJ low side for me

**Comment by rusefillc** [comment]
Sorry we have to do this again, this time I will order without INJ low side for sure

See also recent https://github.com/rusefi/hellen-NB1-issues/issues/26
