### ISSUE TITLE
Aux analog inputs removed from MAP sensor options, why?

### ISSUE THREAD

**Issue by ElDominio** [rusefi/hellen121nissan-issues#24]
![image](https://user-images.githubusercontent.com/5685108/213954397-e383dfc0-d59a-42f7-ac80-3a0c4be6418a.png)

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/213956076-777357d4-fb8c-4af4-8816-55d7c1ed3f11.png)

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/commit/08e9af15664ab2cfc0ae37df78de7c8f8505fd92 was the change

**Comment by rusefillc** [comment]
the change was due to same analog input mentioned twice
I've reverted to original naming but technically "Aux AnInput 1" etc are available in the affected version
