### ISSUE TITLE
Cranking issues, VVT angle not consistent

### ISSUE THREAD

**Issue by ElDominio** [rusefi/hellen121nissan-issues#26]
https://rusefi.com/online/view.php?log=1197

Tune and log are there
VVT angle sometimes is not correct/changes while cranking. Car is drivable by disabling VVT sync after 400RPM

**Comment by rusefillc** [comment]
Could be lazy hall @mck1117 ?

@ElDominio can you please try flipping "invert cam inputs" which I hope is the way to read the other front?

https://rusefi.com/online/view.php?msq=1424&dialog=triggerConfiguration

**Comment by rusefillc** [comment]
@ElDominio any news? any new logs/new tune?

**Comment by ElDominio** [comment]
Very difficult to replicate; setting to TRUE caused significantly worse behavior.

In FALSE, it might be one out of 20 that doesn't read correctly while cranking.

**Comment by ElDominio** [comment]
closed because not consistent enough to be actively worrying about it
