### ISSUE TITLE
Document pin 68 - Suggest removing R8 From Future board spin

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen121nissan-issues#3]
GND? 5v? what's the deal?

![image](https://user-images.githubusercontent.com/48498823/123735167-b7674c80-d86c-11eb-8567-164ff242fa4b.png)

**Comment by Qwerty-OFF** [comment]
https://github.com/rusefi/rusefi/wiki/Hellen-121-Nissan#vehicle-specific-jumpers

**Comment by rusefillc** [comment]
I am unable to filter R7 R8 on ibom https://rusefi.com/docs/ibom/hellen121nissan-b-ibom.html

**Comment by rusefillc** [comment]
here's BOM line
```
"Jumper-Pad-Pad","R1, R2, R3, R4, R5, R6, R7, R8, R9, R10, R11, R12, R13, R14, R15, R16, R17, R18, R19, R20, R21, R22, R23, R24, R25, R26, R27, R28, R29, R30, R31, R32, R33, R34, R35, R36, R37, R38, R39, R40, R41, R42, R43, R50, R51, R52, R70, R71, R72","PAD-0805-PAD","C17477"
```

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/124026838-2ef9c080-d9c0-11eb-929c-055cae3a85ee.png)

**Comment by rusefillc** [comment]
@pk386 can you please help me understand me this? what's this pin about? why the variation?

**Comment by pk386** [comment]
![image](https://user-images.githubusercontent.com/13985751/124417040-eaeb2080-dd1d-11eb-990a-663f8d9fa26f.png)

Says its one of the inputs for the Power steering pressure sensor? (2011 x-trerra VQ40)


I assume the pin 68 on the ECM is the one you are referring to?

**Comment by pk386** [comment]
![image](https://user-images.githubusercontent.com/13985751/124417564-06a2f680-dd1f-11eb-9558-5cd5f00127ec.png)
Pin 12(ECM)  Pin 2 (Power steering) = Power steering signal 0.5v->4.5Vdc 
Pin 68 (ECM)  pin 3 (Power steering)= +5V power supply from ECM 
Pin 1 (Power steering) = Sensor ground.

![image](https://user-images.githubusercontent.com/13985751/124418027-1ff87280-dd20-11eb-9b4f-4a5a217c3a78.png)

**Comment by rusefillc** [comment]
@pk386 see the weird thing at https://github.com/rusefi/rusefi/wiki/Hellen-121-Nissan#vehicle-specific-jumpers

somehow this pin seems to be wired differently between different vehicles? Are we misunderstanding the schematics? which of the four R7 R8 configurations is the most proper?

**Comment by pk386** [comment]
from the X-terra schematics:
(Note: M-> connects to <-M 
and     X-> connects to <-X)
![image](https://user-images.githubusercontent.com/13985751/124527038-162b4980-ddca-11eb-88bd-e5455ba7fce9.png) 
![image](https://user-images.githubusercontent.com/13985751/124527071-2b07dd00-ddca-11eb-8075-a04ade3aa6ae.png) 
![image](https://user-images.githubusercontent.com/13985751/124527082-39ee8f80-ddca-11eb-9433-8b8d26dda8c1.png)

so all these sensors are share a ground with Pin 67.

Looking at the 2003/2005 350z, the 2011 X-terra, the 2005 Altima and 2005 Maxima... it is safe to assume that **R7 be populated with a 0ohm resistor** (or fuse) on ALL boards

R8 Should NOT be populated (or DNP)

_Suggest removing R8 From Future board spin_

**Comment by pk386** [comment]
the 2005 350z manual states it best in the following pin  descriptions:
![image](https://user-images.githubusercontent.com/13985751/124527730-e715d780-ddcb-11eb-8eae-988dc7e5a984.png)

**Comment by Qwerty-OFF** [comment]
Removed. Pin 68 now is +5V.
