### ISSUE TITLE
Aux P70 and P71 don't show in yaml, how to call from Lua

### ISSUE THREAD

**Issue by ElDominio** [rusefi/hellen121nissan-issues#30]
I want to do map switch, but I need to know how do readPin on these pins from Lua

**Comment by rusefillc** [comment]
@ElDominio where can I find those P70 and P71? board rev?

**Comment by ElDominio** [comment]
<img width="676" alt="image" src="https://github.com/rusefi/hellen121nissan-issues/assets/5685108/edc75a39-ecc4-4b07-8075-515e58b1f47e">

https://github.com/rusefi/rusefi/wiki/Hellen-121-Nissan

revBefore they had molex, one of the first units

**Comment by rusefillc** [comment]
rev A
![image](https://github.com/rusefi/hellen121nissan-issues/assets/48498823/67a7f43f-4ffe-4eb1-91e3-7ded891ed336)

**Comment by rusefillc** [comment]
rev current with molex

![image](https://github.com/rusefi/hellen121nissan-issues/assets/48498823/f4b1f9de-813d-490b-a239-462ed37129b3)

**Comment by ElDominio** [comment]
how would I call it in Lua? 
readPin("PF70")?

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/wiki/Hellen-121-Nissan now says "DINx" and .yaml has those

https://github.com/rusefi/rusefi/commit/7182bd868ea5e0368b893cfffcec526f15b3e0b9

**Comment by ElDominio** [comment]
Lua scripting page has made it clear on how to call pins
