### ISSUE TITLE
WBO white connector - pins are sticking out

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen121nissan-issues#6]
back side of while connector hits the rubber on OEM ECU

**Comment by rusefillc** [comment]
First I will try simply trimming the back side, maybe no PCB changes would be needed

**Comment by Qwerty-OFF** [comment]
Need to make changes?

**Comment by rusefillc** [comment]
no need to fix yet, trimming works for now

**Comment by Qwerty-OFF** [comment]
@rusefillc Need to change something?

**Comment by rusefillc** [comment]
Will keep trimming for now.

**Comment by rusefillc** [comment]
The only way to fix I can think of would be to move into an area where case is not touching the PCB

**Comment by Qwerty-OFF** [comment]
What if install right angle connector like this?
![image](https://user-images.githubusercontent.com/4116383/189434453-fdf9a3f1-c5e7-4ad6-a4ff-857ccad7262d.png)
Perhaps this SMD connector is suitable (C2845700)
![image](https://user-images.githubusercontent.com/4116383/189434959-5071bbab-7f31-4654-9a3f-916b59426708.png)

**Comment by rusefillc** [comment]
@Qwerty-OFF i love C2845700

**Comment by Qwerty-OFF** [comment]
![Uploading image.png…]()

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/191126439-4f532d4e-75be-4ed9-bf09-d1d69157c175.png)
